rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2

gemfile:
  - gemfiles/rails_4.1.gemfile

matrix:
  include:
    - rvm: 1.9.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: jruby
      gemfile: gemfiles/mongoid_4.0.gemfile

services:
  - mongodb
